apiVersion: batch/v1
kind: Job
metadata:
  name: devguard-job
  namespace: NAMESPACE_PLACEHOLDER     # ← naya placeholder!
spec:
  template:
    spec:
      containers:
      - name: devguard
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        env:
        - name: DOCKER_ENV
          value: "true"
        - name: ENVIRONMENT
          value: "ENV_PLACEHOLDER"      # ← bonus: pod ko bhi pata chale
      restartPolicy: Never
  backoffLimit: 2
