apiVersion: batch/v1
kind: Job
metadata:
  name: devguard-job
spec:
  template:
    spec:
      containers:
      - name: devguard
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        env:
        - name: DOCKER_ENV
          value: "true"
        - name: LOG_DIR
          value: "/app/logs"
      restartPolicy: Never
  backoffLimit: 2
